### ISSUE TITLE
Race condition when loading AsyncResult from dump file

### ISSUE THREAD

**Issue by harryjubb** [goerz/clusterjob#3]
I'm using `clusterjob` with `doit` and am finding that in some cases, I get an error because of the delay between submitting the job and it being accepted appearing in (in this case) `bjobs -a`:

```
PythonAction Error
Traceback (most recent call last):
  File "/path/to/repo/virtualenv/lib/python3.6/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/path/to/repo/utilities.py", line 117, in wait_for_clusterjob
    run.wait()
  File "/path/to/repo/virtualenv/lib/python3.6/site-packages/clusterjob/__init__.py", line 1013, in wait
    status = self.status
  File "/path/to/repo/virtualenv/lib/python3.6/site-packages/clusterjob/__init__.py", line 938, in status
    status = self.backend.get_status(response, finished=False)
  File "/path/to/repo/virtualenv/lib/python3.6/site-packages/clusterjob/backends/lsf.py", line 103, in get_status
    status = line[status_pos:].split()[0]
IndexError: list index out of range
```

It seems to be that because the job ID doesn't exist yet in the `bjobs -a` list, it can't be parsed from there so it raises the `IndexError`.

My dodo file roughly follows the doit example in the documentation, I'm running a command on a large number of data accessions, and my tasks are roughly of the form:

```
yield {
    'name': f'submit_{accession}',
    'actions': [
        (submit_clusterjob, (command, accession), {})
    ]
}

yield {
    'name': f'wait_{accession}',
    'actions': [
        (wait_for_clusterjob, (accession,), {})
    ]
}
```

```
def submit_clusterjob(body, jobname, runfolder, jobargs=(), jobkwargs={}):

    jobscript = clusterjob.JobScript(
        body,
        jobname,
        *jobargs,
        **jobkwargs
    )

    run = jobscript.submit(force=True)
    run.dump(os.path.join(runfolder, jobname))


def wait_for_clusterjob(jobname, runfolder):

    run = clusterjob.AsyncResult.load(os.path.join(runfolder, jobname))
    run.wait()
    os.unlink(os.path.join(runfolder, jobname))
    return run.successful()

```

Is there any way to ensure that the job has been fully submitted and is showing in `bjobs -a` allowing `run.wait`  to be called without a hacky `time.sleep` or similar?

Many thanks,

**Comment by goerz** [comment]
I'll have to look into that. If you activate debug logging via

     import logging
     logging.basicConfig(level=logging.DEBUG)

in your main script, you will be able to see the exact communication with the cluster, that is, which commands are issued when and what their response is. It would be helpful (especially since I don't currently have access to any cluster running LSF) if you could upload that output somewhere. You can obscure identifying information such as user- or hostnames, if necessary.

It's possible that inserting a short sleep somewhere might be a general solution. Very fundamentally, though, all information about the job status has to come from the output of commands issued to the scheduler. Things can really depend on the setup of a particular system: Is the job ID not being known after submission always a sign that it just hasn't fully made it into the system yet, or could it also be a sign that the job has finished? If these two situations (for example) can't be distinguished, that would be a problem. If they can, at the very least you could always subclass the Backend to adapt to the specific setup of that cluster. However, I'd still want to look into this to see if it's a general problem.
